export const CREATE_RECORD = "CREATE_RECORD"

export const SAVE_RECORD = "SAVE_RECORD"

export const DELETE_RECORD = "DELETE_RECORD"

export const FETCH_LOADING = "FETCH_LOADING"

export const FETCH_SUCCESS = "FETCH_SUCCESS"

export const FETCH_FAILED = "FETCH_FAILED"